<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SubtitleCompare.Core</RootNamespace>
    <AssemblyName>SubtitleCompare.Core</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
